name = "wiredan-backend"
main = "worker/index.js"
compatibility_date = "2025-01-01"
account_id = "<YOUR_ACCOUNT_ID>"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "6b6ed34e782c437a80ddb6308a0fee5f"

[d1_databases]
bindings = [
  { name = "D1_BINDING", database_name = "wiredan-db", database_id = "4e80c08b-47f5-4069-94a6-fcc22ac2a546" }
]