name = "wiredan-app"
main = "worker/index.js"
compatibility_date = "2024-01-01"

account_id = "<YOUR_CLOUDFLARE_ACCOUNT_ID>"

# D1 database binding
[[d1_databases]]
binding = "WIREDAN_DB"
database_name = "wiredan-db"
database_id = "4e80c08b-47f5-4069-94a6-fcc22ac2a546"

# KV binding for worker
[[kv_namespaces]]
binding = "WIREDAN_KV"
id = "6b6ed34e782c437a80ddb6308a0fee5f"

# Pages deployment
[site]
bucket = "./frontend"
build_command = ""